// <copyright file="IGame.cs" company="Night Circle">
// zlib license
//
// Copyright (c) 2025 Danny Solivan, Night Circle
//
// This software is provided 'as-is', without any express or implied
// warranty. In no event will the authors be held liable for any damages
// arising from the use of this software.
//
// Permission is granted to anyone to use this software for any purpose,
// including commercial applications, and to alter it and redistribute it
// freely, subject to the following restrictions:
//
// 1. The origin of this software must not be misrepresented; you must not
//    claim that you wrote the original software. If you use this software
//    in a product, an acknowledgment in the product documentation would be
//    appreciated but is not required.
// 2. Altered source versions must be plainly marked as such, and must not be
//    misrepresented as being the original software.
// 3. This notice may not be removed or altered from any source distribution.
// </copyright>

using System;

namespace Night
{
  /// <summary>
  /// Interface for a game that can be run by the Night Engine.
  /// Game developers will implement this interface in their main game class.
  /// </summary>
  public interface IGame
  {
    /// <summary>
    /// Called exactly once when the game starts for loading resources.
    /// </summary>
    void Load();

    /// <summary>
    /// Callback function used to update the state of the game every frame.
    /// </summary>
    /// <param name="deltaTime">The time elapsed since the last frame, in seconds.</param>
    void Update(double deltaTime);

    /// <summary>
    /// Callback function used to draw on the screen every frame.
    /// </summary>
    void Draw();

    /// <summary>
    /// Callback function triggered when a key is pressed.
    /// </summary>
    /// <param name="key">The logical key symbol that was pressed.</param>
    /// <param name="scancode">The physical key (scancode) that was pressed.</param>
    /// <param name="isRepeat">True if this is a key repeat event, false otherwise.</param>
    void KeyPressed(KeySymbol key, KeyCode scancode, bool isRepeat);

    /// <summary>
    /// Callback function triggered when a key is released.
    /// </summary>
    /// <param name="key">The logical key symbol that was released.</param>
    /// <param name="scancode">The physical key (scancode) that was released.</param>
    void KeyReleased(KeySymbol key, KeyCode scancode);

    /// <summary>
    /// Callback function triggered when a mouse button is pressed.
    /// </summary>
    /// <param name="x">The x-coordinate of the mouse cursor relative to the window.</param>
    /// <param name="y">The y-coordinate of the mouse cursor relative to the window.</param>
    /// <param name="button">The mouse button that was pressed.</param>
    /// <param name="istouch">True if the event was generated by a touch input device, false otherwise.</param>
    /// <param name="presses">The number of clicks (1 for single-click, 2 for double-click, etc.).</param>
    void MousePressed(int x, int y, MouseButton button, bool istouch, int presses);

    /// <summary>
    /// Callback function triggered when a mouse button is released.
    /// </summary>
    /// <param name="x">The x-coordinate of the mouse cursor relative to the window.</param>
    /// <param name="y">The y-coordinate of the mouse cursor relative to the window.</param>
    /// <param name="button">The mouse button that was released.</param>
    /// <param name="istouch">True if the event was generated by a touch input device, false otherwise.</param>
    /// <param name="presses">The number of clicks (typically 1 for release, but may vary).</param>
    void MouseReleased(int x, int y, MouseButton button, bool istouch, int presses);

    /// <summary>
    /// Callback function triggered when a joystick is connected.
    /// </summary>
    /// <param name="joystick">The Joystick object representing the connected device.</param>
    void JoystickAdded(Joystick joystick);

    /// <summary>
    /// Callback function triggered when a joystick is disconnected.
    /// </summary>
    /// <param name="joystick">The Joystick object representing the disconnected device.</param>
    void JoystickRemoved(Joystick joystick);

    /// <summary>
    /// Callback function triggered when a joystick axis moves.
    /// </summary>
    /// <param name="joystick">The Joystick object.</param>
    /// <param name="axis">The index of the axis that moved.</param>
    /// <param name="value">The new value of the axis, typically in the range -1.0 to 1.0.</param>
    void JoystickAxis(Joystick joystick, int axis, float value);

    /// <summary>
    /// Callback function triggered when a joystick button is pressed.
    /// </summary>
    /// <param name="joystick">The Joystick object.</param>
    /// <param name="button">The index of the button that was pressed.</param>
    void JoystickPressed(Joystick joystick, int button);

    /// <summary>
    /// Callback function triggered when a joystick button is released.
    /// </summary>
    /// <param name="joystick">The Joystick object.</param>
    /// <param name="button">The index of the button that was released.</param>
    void JoystickReleased(Joystick joystick, int button);

    /// <summary>
    /// Callback function triggered when a joystick hat direction changes.
    /// </summary>
    /// <param name="joystick">The Joystick object.</param>
    /// <param name="hat">The index of the hat that changed.</param>
    /// <param name="direction">The new direction of the hat.</param>
    void JoystickHat(Joystick joystick, int hat, JoystickHat direction);

    /// <summary>
    /// Callback function triggered when a virtual gamepad axis is moved.
    /// </summary>
    /// <param name="joystick">The Joystick object (which is also a gamepad).</param>
    /// <param name="axis">The virtual gamepad axis that moved.</param>
    /// <param name="value">The new value of the axis, typically in the range -1.0 to 1.0.</param>
    void GamepadAxis(Joystick joystick, GamepadAxis axis, float value);

    /// <summary>
    /// Callback function triggered when a virtual gamepad button is pressed.
    /// </summary>
    /// <param name="joystick">The Joystick object (which is also a gamepad).</param>
    /// <param name="button">The virtual gamepad button that was pressed.</param>
    void GamepadPressed(Joystick joystick, GamepadButton button);

    /// <summary>
    /// Callback function triggered when a virtual gamepad button is released.
    /// </summary>
    /// <param name="joystick">The Joystick object (which is also a gamepad).</param>
    /// <param name="button">The virtual gamepad button that was released.</param>
    void GamepadReleased(Joystick joystick, GamepadButton button);

    /// <summary>
    /// The main callback function, containing the main loop logic.
    /// A sensible default is used when not overridden.
    /// This function, when obtained, should be called repeatedly by the engine's main loop.
    /// </summary>
    /// <returns>
    /// A function (mainLoopIteration) which handles one frame, including events and rendering, when called.
    /// The returned mainLoopIteration function returns an optional integer:
    /// - null: Continue the game loop.
    /// - int value: Exit the game loop with the specified status code.
    /// </returns>
    Func<int?> Run();

    /// <summary>
    /// Callback function triggered when the game is about to close.
    /// </summary>
    /// <returns>
    /// False to cancel the quit attempt (and continue running the game),
    /// true to allow the game to close.
    /// </returns>
    bool Quit();
  }
}
